/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/ti3/grace_2_20_01_12/packages/ti/mcu/msp430/csl/interrupt_vectors/InterruptVectors_init.xdt
 */
#include <msp430.h>

/* USER CODE START (section: InterruptVectors_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: InterruptVectors_init_c_prologue) */

/*
 *  ======== InterruptVectors_graceInit ========
 */
void InterruptVectors_graceInit(void)
{
}


/* Interrupt Function Prototypes */


/*
 *  ======== PORT2 Interrupt Service Routine ========
 *
 * Here are several important notes on using PORTx interrupt Handler:
 *
 * 1. User must explicitly clear the port interrupt flag before exiting
 *
 *    PxIFG &= ~(BITy);
 *
 * 2. User could also exit from low power mode and continue with main
 *    program execution by using the following instruction before exiting
 *    this interrupt handler.
 *
 *    __bic_SR_register_on_exit(LPMx_bits);
 *
 */
#pragma vector=PORT2_VECTOR
__interrupt void PORT2_ISR_HOOK(void)
{
    /* USER CODE START (section: PORT2_ISR_HOOK) */
	acc_isr();
    /* USER CODE END (section: PORT2_ISR_HOOK) */
}
/*
 * ======== Preserved user code snippets ========
 */
#if 0
    /* USER CODE START (section: USCI0RX_ISR_HOOK) */
//	acc_isr();
    /* USER CODE END (section: USCI0RX_ISR_HOOK) */

/* USER CODE START (section: USCI0TX_ISR_HOOK) */
    /* replace this comment with your code */
    /* USER CODE END (section: USCI0TX_ISR_HOOK) */

/* USER CODE START (section: PORT1_ISR_HOOK) */
    /* replace this comment with your code */
    /* USER CODE END (section: PORT1_ISR_HOOK) */
#endif
